
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates S3 bucket"

Parameters:
  S3BucketName:
    Description: Enter S3 bucket name
    Type: String
  EncryptionType:
    Description: Select the encryption type for the S3 bucket
    Type: String
    Default: SSE-S3
    AllowedValues:
      - SSE-S3
      - SSE-KMS
  

Conditions:
  IsSSE-S3: !Equals [!Ref EncryptionType, SSE-S3]
  IsSSE-KMS: !Equals [!Ref EncryptionType, SSE-KMS]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              "Fn::If":
                - IsSSE-S3
                - SSEAlgorithm: AES256
                - !Ref "AWS::NoValue"
              "Fn::If":
                - IsSSE-KMS
                - SSEAlgorithm: aws:kms
                - !Ref "AWS::NoValue"
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
  EncryptionTypeOutput:
    Value: !Ref 'EncryptionType'
  BucketARN:
    Value: !GetAtt 'S3Bucket.Arn'
