AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates S3 bucket"

Parameters:
  S3BucketName:
    Description: Enter S3 bucket name
    Type: String
    MinLength: 3
    MaxLength: 10
    AllowedPattern: "[A-Za-z]+"
  EncryptionType:
    Description: Select the encryption type for the S3 bucket
    Type: String
    Default: SSE-S3
    AllowedValues:
      - SSE-S3
      - KMS

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - ServerSideEncryptionByDefault:
      #         SSEAlgorithm: !Ref EncryptionType

Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
  EncryptionTypeOutput:
    Value: !Ref 'EncryptionType'
  BucketARN:
    Value: !GetAtt 'S3Bucket.Arn'

